### ISSUE TITLE
[Bug][ONNX] cann't parse strides for LpPool

### ISSUE THREAD

**Issue by jikechao** [apache/tvm#14661] opened 2023-04-18 17:13 UTC
For the below onnx model with LpPool, we can see that no `strides` attribute in LpPool. However, tvm frontend try to parse this attribute, and throw an error: `KeyError: 'strides'`. By analysis, the crash is caused by the [node.attribute] https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/onnx.py#:~:text=attr%20%3D%20self._parse_attr(node.attribute) cannot get the `strides` attribute and lead to a crash when execute `attr["strides"]` in this [line](https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/onnx.py#:~:text=data%2C-,attr%5B%22strides%22%5D%2C,-attr%5B%22kernel_shape).

### model structure
![image](https://user-images.githubusercontent.com/29506758/234762020-7ebaa8f0-2798-4f65-9b2f-9ca46a96c8d0.png)

### Crash message
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    irmod, params = relay.frontend.from_onnx(model, {'x': (1, 3, 32, 32)}, freeze_params=True)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 7347, in from_onnx
    mod, params = g.from_onnx(graph, opset)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 6964, in from_onnx
    self._construct_nodes(graph)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 7079, in _construct_nodes
    op = self._convert_operator(op_name, inputs, attr, self.opset)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 7205, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 1999, in _impl_v1
    attr["strides"],
KeyError: 'strides'
```

### Steps to reproduce
1. download the [lppool_model.onnx](https://github.com/jikechao/onnx_models/blob/main/lppool_model.onnx)
2. execute the script.
```
import onnx
from tvm import relay

onnx_model_path = "lppool_model.onnx"
model = onnx.load(onnx_model_path)
irmod, params = relay.frontend.from_onnx(model, {'x': (1, 3, 32, 32)}, freeze_params=True)
```

### Triage
* frontend:onnx

cc @KJlaccHoeUM9l

**Comment by jikechao** [comment] 2023-04-20 03:02
Hello, @AndrewZhaoLuo @vvchernov :
It checked the source code, and Lppool is supported by onnx converter. I cannot figure out why `strides` attribute cannot be parsed. Is it my wrong usage or a bug?

**Comment by AndrewZhaoLuo** [comment] 2023-04-26 18:56
Hey @jikechao I will take a look today or tomorrow.

**Comment by AndrewZhaoLuo** [comment] 2023-04-26 21:01
Oddly enough I am not able to reproduce your mod. Your code runs fine on my machine:

Resulting printout from `irmod`
```
Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
def @main(%x: Tensor[(1, 3, 32, 32), float32] /* ty=Tensor[(1, 3, 32, 32), float32] span=LpPool_0.x:0:0 */) -> Tensor[(1, 3, 10, 10), float32] {
  %0 = power(%x, 2f /* ty=float32 span=LpPool_0:0:0 */) /* ty=Tensor[(1, 3, 32, 32), float32] span=LpPool_0:0:0 */;
  %1 = nn.avg_pool2d(%0, pool_size=[5, 5], strides=[3, 3], padding=[0, 0, 0, 0], count_include_pad=True) /* ty=Tensor[(1, 3, 10, 10), float32] span=LpPool_0:0:0 */;
  %2 = abs(%1) /* ty=Tensor[(1, 3, 10, 10), float32] span=LpPool_0:0:0 */;
  %3 = multiply(%2, 25f /* ty=float32 span=LpPool_0:0:0 */) /* ty=Tensor[(1, 3, 10, 10), float32] span=LpPool_0:0:0 */;
  power(%3, 0.5f /* ty=float32 span=LpPool_0:0:0 */) /* ty=Tensor[(1, 3, 10, 10), float32] span=LpPool_0:0:0 */
}
```

What version of onnx are you using?

```
keras2onnx==1.7.0
onnx==1.12.0
onnx-graphsurgeon==0.3.25
onnx-simplifier==0.3.6
onnx-tf==1.9.0
onnxconverter-common==1.9.0
onnxmltools==1.11.1
onnxoptimizer==0.2.6
onnxruntime==1.13.1
onnxruntime-gpu==1.13.1
onnxruntime-tools==1.7.0
skl2onnx==1.11.2
tf2onnx==1.9.2
tflite2onnx==0.4.0
```

Here is my `pip freeze | grep onnx`

**Comment by jikechao** [comment] 2023-04-27 04:53
@AndrewZhaoLuo Thanks for you review, It's my mistake to provide a wrong model link. I have corrected the bug description and modified the model link. You can download correct model via this link：  
https://github.com/jikechao/onnx_models/blob/main/lppool_model.onnx  and the provided script is same as before.

**Comment by AndrewZhaoLuo** [comment] 2023-04-27 15:59
Ah the answer is as of opset 11, strides is an optional attribute. If it is not present, you just treat it as 1 along every spatial axis. 

Should be simple to fix, but basically you replace `attrs['strides']` with something like `attrs.get('strides', [1] * num_spatial_dims)`. If you want to open up a fix that is cool. If not I can do it too.

**Comment by AndrewZhaoLuo** [comment] 2023-05-01 16:29
#14740 has merged

**Closed by AndrewZhaoLuo** 2023-05-01 16:29 UTC
Labels: type: bug, needs-triage
