### ISSUE TITLE
[TEST][FLAKY] tests/python/relay/test_op_level5.py::test_crop_and_resize

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7470] opened 2021-02-18 14:40 UTC
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7469/3/pipeline/258

**Comment by tqchen** [comment] 2021-02-18 14:41
cc @masahi can you please take a look?

**Comment by K1504296** [comment] 2021-04-18 17:24
Hello,
Any updates on this? I'm consistently running into a similar error in verify_crop_and_resize() on aarch64 devices when running task_python_integration.py.

```
tests/python/relay/test_op_level5.py:163: in verify_crop_and_resize
tvm.testing.assert_allclose(op_res.asnumpy(), ref_res, rtol=1e-3, atol=1e-04)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
actual = array([[[[0.7755371 , 0.36136428, 0.49826235],
[0.63967055, 0.5373034 , 0.4265945 ],
[0.3071108 , 0....17595],
[0.11378219, 0.1943004 , 0.47557598],
[0.63771987, 0.7763749 , 0.4037985 ]]]], dtype=float32)
desired = array([[[[0.77553688, 0.36136451, 0.49826134],
[0.63966878, 0.53730296, 0.42659563],
[0.30710987, 0.... , 0. ],
[0. , 0. , 0. ],
[0. , 0. , 0. ]]]])
rtol = 0.001, atol = 0.0001
 
def assert_allclose(actual, desired, rtol=1e-7, atol=1e-7):
"""Version of np.testing.assert_allclose with `atol` and `rtol` fields set
in reasonable defaults.
 
Arguments `actual` and `desired` are not interchangable, since the function
compares the `abs(actual-desired)` with `atol+rtol*abs(desired)`. Since we
often allow `desired` to be close to zero, we generally want non-zero `atol`.
"""
actual = np.asanyarray(actual)
desired = np.asanyarray(desired)
np.testing.assert_allclose(actual.shape, desired.shape)
> np.testing.assert_allclose(actual, desired, rtol=rtol, atol=atol, verbose=True)
E AssertionError:
E Not equal to tolerance rtol=0.001, atol=0.0001
E
E Mismatched elements: 90 / 3600 (2.5%)
E Max absolute difference: 0.98851174
E Max relative difference: 9.95329627e-05
E x: array([[[[0.775537, 0.361364, 0.498262],
E [0.639671, 0.537303, 0.426594],
E [0.307111, 0.262529, 0.711934],...
E y: array([[[[0.775537, 0.361365, 0.498261],
E [0.639669, 0.537303, 0.426596],
E [0.30711 , 0.262528, 0.711934],...
 
python/tvm/testing.py:82: AssertionError
```

**Comment by masahi** [comment] 2021-04-19 08:38
I cannot reproduce this error on x86 or vulkan. ` Max absolute difference: 0.98851174` indices this is not simply an accuracy problem, there is something wrong in topi or reference implementation

cc @yongwww

**Comment by K1504296** [comment] 2021-04-21 12:54
Hello,
When running with img shape 224 x 224 on aarch64 this error occurs. This doesn't occur with other image sizes (244, 488 255, 128, 488 are all okay.) and it doesn't matter if it's nhcw or nchw.

Looking at the ref_res array produced by tvm.topi.testing.crop_and_resize_python() there are empty entries at the end of the array:
ref_res:
```
   [0.44745926 0.28042721 0.36698769]]

  [[0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   ...
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]]]
```
op_res.asnumpy() :
```
  [0.44745678 0.28042898 0.3669866 ]]

  [[0.97783726 0.42928934 0.27261683]
   [0.4878334  0.8326363  0.23196666]
   [0.47669002 0.68640965 0.14338642]
   ...
   [0.5510204  0.8910937  0.38670242]
   [0.32497528 0.5985708  0.5816476 ]
   [0.51059437 0.6367534  0.17070939]]]]
```

Any ideas on why this would be occuring on aarch64?

**Comment by denise-k** [comment] 2021-09-27 21:07
Hi folks, is this still active?

**Comment by masahi** [comment] 2021-09-28 03:22
This is not reproducible on my end and I haven't seen it in CI jobs. I think we can close this.

@K1504296 Feel free to reopen if the error persists on aarch64.

**Closed by masahi** 2021-09-28 03:22 UTC
Labels: test: flaky
