### ISSUE TITLE
[BUG][CodeGenC]“tvm_call_packed” crashes when build with target “c”

### ISSUE THREAD

**Issue by zhuwenxi** [apache/tvm#7596] opened 2021-03-05 02:14 UTC
Forum discussion thread attached here: https://discuss.tvm.apache.org/t/bug-codegenc-tvm-call-packed-crashes-when-build-with-target-c/9291

@tqchen Could you bridge me someone who's familiar with C backend to look into this? I highly doubt this is a known issue.

**Comment by leeexyz** [comment] 2021-03-07 05:35
Hi @zhuwenxi , that's a bug. Actually, this is a case from tutorial **extern op**, [link ](https://tvm.apache.org/docs/tutorials/language/extern_op.html). After investigating, I have found this issue was introduced by #5417. See [diff](https://github.com/apache/tvm/commit/8d7249688771bb6806595931586d95648036f383?branch=8d7249688771bb6806595931586d95648036f383&diff=unified#diff-68d4c81453bf10caf7ae867ee644de009e7fed808ce871b54364d27134e920e7R186-R194).

You can comment out this ICHECK as a workaround.
```c++
CHECK(GetUniqueName(packed_func_name) == packed_func_name) <<
        "Expected name " << packed_func_name << " to not be taken";
```

**Comment by tqchen** [comment] 2021-03-07 23:37
cc @areusch

**Comment by zhuwenxi** [comment] 2021-03-09 11:59
@leeexyz It works when I comment out the ICHECK line, but only for "tvm.build()". It still crashes when trying to run the module:
![image](https://user-images.githubusercontent.com/4969797/110467406-efa61c00-8111-11eb-880a-83d45b2c7665.png)

Below is my code to reproduce the crash:
<pre>
import tvm
from tvm import te

n = 1024
l = 128
m = 235
bias = te.var("bias", dtype="float32")`
A = te.placeholder((n, l), name="A")`
B = te.placeholder((l, m), name="B")`
C = te.extern(`
    (n, m),
    [A, B],
    lambda ins, outs: tvm.tir.call_packed(`
        "tvm.contrib.cblas.matmul", ins[0], ins[1], outs[0], False, False`
    ),`
    name="C",`
)
D = te.compute(C.shape, lambda i, j: C[i, j] + bias, name="D")`
s = te.create_schedule(D.op)`

ctx = tvm.cpu(0)`
f = tvm.build(s, [A, B, D, bias], "c")
a = tvm.nd.array(np.random.uniform(size=(n, l)).astype(A.dtype), ctx)
b = tvm.nd.array(np.random.uniform(size=(l, m)).astype(B.dtype), ctx)
d = tvm.nd.array(np.zeros((n, m), dtype=D.dtype), ctx)
bb = 10.0
f(a, b, d, bb)
</pre>

**Comment by leeexyz** [comment] 2021-03-10 01:56
> @leeexyz It works when I comment out the ICHECK line, but only for "tvm.build()". It still crashes when trying to run the module:
> ![image](https://user-images.githubusercontent.com/4969797/110467406-efa61c00-8111-11eb-880a-83d45b2c7665.png)
> 
> Below is my code to reproduce the crash:
> 
> import tvm
> from tvm import te
> 
> n = 1024
> l = 128
> m = 235
> bias = te.var("bias", dtype="float32")`
> A = te.placeholder((n, l), name="A")`
> B = te.placeholder((l, m), name="B")`
> C = te.extern(`
>     (n, m),
>     [A, B],
>     lambda ins, outs: tvm.tir.call_packed(`
>         "tvm.contrib.cblas.matmul", ins[0], ins[1], outs[0], False, False`
>     ),`
>     name="C",`
> )
> D = te.compute(C.shape, lambda i, j: C[i, j] + bias, name="D")`
> s = te.create_schedule(D.op)`
> 
> ctx = tvm.cpu(0)`
> f = tvm.build(s, [A, B, D, bias], "c")
> a = tvm.nd.array(np.random.uniform(size=(n, l)).astype(A.dtype), ctx)
> b = tvm.nd.array(np.random.uniform(size=(l, m)).astype(B.dtype), ctx)
> d = tvm.nd.array(np.zeros((n, m), dtype=D.dtype), ctx)
> bb = 10.0
> f(a, b, d, bb)

It caused by `CSourceModuleNode` does not support to get function `runtime::symbol::tvm_module_main`. You can compare with the `LLVMModuleNode` and add it.
> src/target/source/source_module.cc:src/target/source/source_module.cc
> src/target/llvm/llvm_module.cc:GetFunction

**Comment by zhuwenxi** [comment] 2021-03-10 07:44
@leeexyz , I looked into the test cases for tvmc (https://github.com/apache/tvm/blob/main/tests/python/unittest/test_target_codegen_c_host.py#L36) and found that all the cases export their module as library and then load the module, before actually run the module, like this:
<pre>
mhost = tvm.build(s, [A, B, C], "c", name="test_fadd")
**mhost.export_library(path_dso)
m = tvm.runtime.load_module(path_dso)**
fadd = m["test_fadd"]
fadd(a, b, c)
</pre> 

My question is, is this a desired behavior, rather than a bug that tvmc does not support to run a module directly?
<pre>
# Following code pattern is not desired in tvmc?
f = tvm.build(s, [A, B, D, bias], "c")
f(a, b, d, bb)
</pre>

**Comment by leeexyz** [comment] 2021-03-10 08:48
> @leeexyz , I looked into the test cases for tvmc (https://github.com/apache/tvm/blob/main/tests/python/unittest/test_target_codegen_c_host.py#L36) and found that all the cases export their module as library and then load the module, before actually run the module, like this:
> 
> mhost = tvm.build(s, [A, B, C], "c", name="test_fadd")
> **mhost.export_library(path_dso)
> m = tvm.runtime.load_module(path_dso)**
> fadd = m["test_fadd"]
> fadd(a, b, c)
> My question is, is this a desired behavior, rather than a bug that tvmc does not support to run a module directly?
> 
> # Following code pattern is not desired in tvmc?
> f = tvm.build(s, [A, B, D, bias], "c")
> f(a, b, d, bb)

I think it does not support it, namely, you cannot run `CSourceModule` directly.

**Comment by zhuwenxi** [comment] 2021-03-18 06:33
> Hi @zhuwenxi , that's a bug. Actually, this is a case from tutorial **extern op**, [link ](https://tvm.apache.org/docs/tutorials/language/extern_op.html). After investigating, I have found this issue was introduced by #5417. See [diff](https://github.com/apache/tvm/commit/8d7249688771bb6806595931586d95648036f383?branch=8d7249688771bb6806595931586d95648036f383&diff=unified#diff-68d4c81453bf10caf7ae867ee644de009e7fed808ce871b54364d27134e920e7R186-R194).
> 
> You can comment out this ICHECK as a workaround.
> 
> ```c++
> CHECK(GetUniqueName(packed_func_name) == packed_func_name) <<
>         "Expected name " << packed_func_name << " to not be taken";
> ```

@leeexyz I found that 1) comment the ICHECK line 2) use export_library() and load_module() didn't solve all the problem. Still, the program is not able to compile:
![image](https://user-images.githubusercontent.com/4969797/111582831-5a341780-87f6-11eb-923e-9309228b2729.png)

I think the root cause is "tvm.contrib.cblas.matmul" is not a qualified c variable name. Below is the c source file generated by tvmc backend:
<img width="1558" alt="WeChatWorkScreenshot_c4c8f1de-7a24-4c90-b39c-3e8a7f58088a" src="https://user-images.githubusercontent.com/4969797/111583061-c747ad00-87f6-11eb-8f65-f8097feb35fe.png">

We probably need to do some major change in tvmc to enable packed func call.

**Comment by leeexyz** [comment] 2021-03-18 11:48
@zhuwenxi Did you build tvm with cblas support?

**Comment by zhuwenxi** [comment] 2021-03-19 01:47
> @zhuwenxi Did you build tvm with cblas support?

Yes, definitely.

**Comment by zhuwenxi** [comment] 2021-03-23 02:39
@leeexyz , could you please check my screenshot posted above? This is definitely an issue that a variable named "tvm.contrib.cblas.matmul_packed" generated in the c source file, which is not a qualified c variable name (not allowed to have a "." symbol).

**Comment by leeexyz** [comment] 2021-03-24 06:00
@zhuwenxi Let me try it :)

**Comment by leeexyz** [comment] 2021-03-26 06:56
> @leeexyz , could you please check my screenshot posted above? This is definitely an issue that a variable named "tvm.contrib.cblas.matmul_packed" generated in the c source file, which is not a qualified c variable name (not allowed to have a "." symbol).

Yes, you are right. It was caused by the same PR I mentioned. Try to modify like
```c++
    // src/target/source/codegen_c_host.cc:void CodeGenCHost::VisitExpr_(const CallNode* op, std::ostream& os);
    std::string packed_func_name = GetUniqueName(func_name + "_packed");
    if (declared_globals_.insert(packed_func_name).second) {
      // Still reserve the name among unique names.
      // ICHECK(GetUniqueName(packed_func_name) == packed_func_name)
      //     << "Expected name " << packed_func_name << " to not be taken";
      decl_stream << "static void* " << packed_func_name << " = NULL;\n";
    }
```
and add 
```c++
    // src/target/source/source_module.cc:GetFunction
    } else if (name == runtime::symbol::tvm_module_main) {
      return PackedFunc(
          [sptr_to_self, this](TVMArgs args, TVMRetValue* rv) { *rv = this->func_names_[0]; });
```

**Comment by zhuwenxi** [comment] 2021-03-29 08:13
@leeexyz , Your fix does make some sense to me. but unfortunately it still crashes my test case:
![image](https://user-images.githubusercontent.com/4969797/112805886-c2adaf00-90a8-11eb-9f09-605fb1119991.png)

This is the c source file generated:
![image](https://user-images.githubusercontent.com/4969797/112806119-06a0b400-90a9-11eb-8ccc-e9877b94f3c9.png)

Have you consider to throw a PR to fix all these bunch of problems? All existing approaches we discussed to fix this problem seem incomplete, we probably need some large changes, from an overall perspectives, to make sure it works for all cases.

**Comment by leeexyz** [comment] 2021-03-30 03:24
Hi @zhuwenxi, I'm not sure why introduced the Map `declared_globals_`, it is better to make it more clear before sending a PR. Can you please give me the tests? I'd like to reproduce these issues :)

**Comment by zhuwenxi** [comment] 2021-03-30 05:58
Thanks @leeexyz , this is the code to reproduce the issue.

<pre>
import tvm
from tvm import te
import numpy as np
#from tvm.contrib import utils

n = 1024
l = 128
m = 235
bias = te.var("bias", dtype="float64")
A = te.placeholder((n, l), name="A", dtype="float64")
B = te.placeholder((l, m), name="B", dtype="float64")
C = te.extern(
    (n, m),
    [A, B],
    lambda ins, outs: tvm.tir.call_packed(
        "tvm.contrib.cblas.matmul", ins[0], ins[1], outs[0], False, False
    ),
    name="C",
)
D = te.compute(C.shape, lambda i, j: C[i, j] + bias, name="D")
s = te.create_schedule(D.op)

ctx = tvm.cpu(0)
f = tvm.build(s, [A, B, D, bias], "c", name="test_add")
f.save("gen_c_code.c", "c")
path_dso = "test_add.so"
f.export_library(path_dso)
m = tvm.runtime.load_module(path_dso)
f = m["test_add"]
ctx = tvm.cpu(0)
a = tvm.nd.array(np.random.uniform(size=(n, l)).astype(A.dtype), ctx)
b = tvm.nd.array(np.random.uniform(size=(l, m)).astype(B.dtype), ctx)
d = tvm.nd.array(np.zeros((n, m), dtype=D.dtype), ctx)
bb = 10.0
f(a, b, d, bb)
</pre>

**Comment by zhuwenxi** [comment] 2021-04-13 03:12
Ping @leeexyz, any updates?

**Comment by leeexyz** [comment] 2021-04-15 02:36
> Ping @leeexyz, any updates?

Sorry for the late, I've been busy lately :(. I will try it this week.

**Comment by leeexyz** [comment] 2021-04-15 03:03
@zhuwenxi I modified the C source manually and it can be compiled. I will start the patch soon.

**Comment by leeexyz** [comment] 2021-04-15 06:05
@zhuwenxi Would you please try this quick patch? https://github.com/leeexyz/tvm/commit/7c296af7af7d5af9cf53dd811118adde05bb2699

**Comment by zhuwenxi** [comment] 2021-04-19 11:53
@leeexyz Sure, let me have a try.

**Comment by zhuwenxi** [comment] 2021-04-19 12:07
@leeexyz Cool, it works!

**Comment by tqchen** [comment] 2021-04-26 12:29
Closed by https://github.com/apache/tvm/pull/7911. Thanks @zhuwenxi @leeexyz !

**Closed by tqchen** 2021-04-26 12:29 UTC
