### ISSUE TITLE
[TEST][FLAKY] test_detection_models

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7363] opened 2021-01-28 21:09 UTC
Seems to be quite frequent in recent PRs, might be related to #7346 

https://ci.tlcpack.ai/job/tvm/job/main/495/execution/node/449/log/

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7360/1/pipeline(this one is timeout)

**Comment by tqchen** [comment] 2021-01-28 21:09
cc @zhiics @masahi

**Comment by masahi** [comment] 2021-01-28 21:54
So this a flaky segfault? Not sure how I can reproduce this.

**Comment by tqchen** [comment] 2021-01-28 22:03
based on my current read it could also be a timeout. In which case we need to look into if the detection model itself runs too long and if we could build a faster unittest

**Comment by masahi** [comment] 2021-01-28 22:05
It should definitely run much faster than TF SSD test.

Disabled one of rewrites in https://github.com/apache/tvm/pull/7365. The other rewrite added in #7346 should be harmless. We'll see.

**Comment by zhiics** [comment] 2021-01-29 07:39
Would this also affect the production test cases although I haven't really seen it.

**Comment by zhiics** [comment] 2021-01-29 07:40
Close by @7365

**Comment by masahi** [comment] 2021-01-29 08:02
I ran MaskRCNN with that rewrite countless times, I didn't see any problem. Weird.

**Comment by altanh** [comment] 2021-01-29 08:11
Before we move too far on from this, can someone compare with our experience in fixing this bug? https://github.com/apache/tvm/issues/7010

If there is some hard to find libomp conflict popping up again, it will crash with "Aborted" like seen the first test

**Comment by masahi** [comment] 2021-01-29 08:55
hmm, I see what's common are the use of pytorch, and the way CI dies. But other than that I don't know if two flaky issues are related.

**Comment by tqchen** [comment] 2021-01-29 14:13
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/503/pipeline

**Comment by masahi** [comment] 2021-01-29 14:45
Looking at https://ci.tlcpack.ai/job/tvm/job/main/, after #7346 was merged, things had been stable for some time (https://ci.tlcpack.ai/job/tvm/job/main/487/ to https://ci.tlcpack.ai/job/tvm/job/main/491/). The crash began to happen after https://github.com/apache/tvm/pull/7354, which added const folding on `If` condition, is merged https://ci.tlcpack.ai/job/tvm/job/main/492/. 

The other rewrite in #7346 does involve `If`. Maybe there is something wrong with `If` after the rewrite.

**Comment by masahi** [comment] 2021-01-29 14:49
One thing I'm curious, the crash at CI https://ci.tlcpack.ai/job/tvm/job/main/ is very frequent, while CIs for open PRs do not get crash (except https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7360/1/pipeline/ which was timeout) as far as I see it. I wonder why.

**Comment by altanh** [comment] 2021-01-29 20:24
In the mean time, is there any way to disable pytest capturing while we debug the CI runs? https://github.com/apache/tvm/issues/7017

this might give more information and confirm/rule out the cause being libomp

**Comment by zhiics** [comment] 2021-01-30 00:35
not sure if I understand the question. Do you want to just run the specific test in CI? If so, we can checkout the docker image and run pytest -v tests/python/frontend/pytorch/test_object_detection.py

**Comment by altanh** [comment] 2021-01-30 00:57
Essentially yes, I think checking out the CI image and running `pytest -s tests/python/frontend/pytorch` will hopefully give more information about what is causing the abort (as long as we can reproduce it).

**Comment by masahi** [comment] 2021-01-31 09:32
@tqchen @zhiics I investigated this issue and I think I have a solution. Running `test_object_detection.py` indeed results in a segfault at the end, after correct execution. I didn't notice this segfault before because I was running a different script when I was working on optimizing MaskRCNN.

Now, I wondered why running one script results in the segfault, while the other doesn't, when two scripts do essentially the same thing. And then I remembered the ONNX + PyTorch segfault problem, which was caused by pytorch being imported earlier than ONNX, see https://github.com/onnx/onnx/issues/2394#issuecomment-581638840

`test_object_detection.py` indeed imports pytorch before TVM, while my other script imports TVM first. So I simply swap the import order in `test_object_detection.py` , and the segfault is gone. If I import torch first in my other scripts, segfault now happens, as expected.

Conclusion: When using PyTorch 1.7, always import TVM first, before torch. PR https://github.com/apache/tvm/pull/7380

**Comment by masahi** [comment] 2021-01-31 19:17
hmm still failing. But now it clearly says all tests have passed, but then it died. https://ci.tlcpack.ai/job/tvm/job/main/495/console

I wonder if this is a driver problem on the post-merge CI node, since I don't see this error happening on CIs for the open PRs.

**Comment by masahi** [comment] 2021-01-31 19:28
I reopened https://github.com/apache/tvm/pull/7371 for the final attempt. It disable the other rewrite done in #7346 and the cuda test. 

I don't think rewrites are the problems, but disabling cuda tests should remove the segfault.

**Comment by masahi** [comment] 2021-02-08 05:11
This can be closed now https://ci.tlcpack.ai/job/tvm/job/main/

**Closed by masahi** 2021-02-08 05:11 UTC
Labels: test: flaky
