### ISSUE TITLE
[Bug] [Relay] Error when compiling a simple ONNX model with Abs and PRelu

### ISSUE THREAD

**Issue by luyaor** [apache/tvm#7203] opened 2021-01-04 12:29 UTC
## Description

When compiling following model with TVM, it will error.

The model(with ONNX as frontend) with error is as follows, check bug.onnx in [bug3.zip](https://github.com/apache/tvm/files/5764602/bug3.zip)

![image](https://user-images.githubusercontent.com/7541296/103535413-9af4e380-4ecb-11eb-82d8-d9eb1fd6508e.png)

## Error Log

```
Traceback (most recent call last):
  File "check.py", line 11, in <module>
    mod, params = relay.frontend.from_onnx(onnx_model, {})
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 2806, in from_onnx
    mod, params = g.from_onnx(graph, opset, freeze_params)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 2613, in from_onnx
    op = self._convert_operator(op_name, inputs, attr, opset)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 2721, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 820, in _impl_v1
    input_channels = infer_shape(inputs[0])[1]
IndexError: tuple index out of range
```

### Environment

Python3, with tvm, onnx

tvm version: [`c31e338`](https://github.com/apache/tvm/commit/c31e338d5f98a8e8c97286c5b93b20caee8be602) Wed Dec 9 14:52:58 2020 +0900

1. Download [bug3.zip](https://github.com/apache/tvm/files/5764602/bug3.zip)

2. Run `python check.py`.

**Comment by jwfromm** [comment] 2021-01-05 04:12
This bug is also fixed in #7208 and was caused by the same issue as #7202.

**Closed** 2021-01-05 08:26 UTC
