### ISSUE TITLE
[CI Problem]  [Checks API] No suitable checks publisher found.

### ISSUE THREAD

**Issue by cconvey** [apache/tvm#12602] opened 2022-08-25 15:22 UTC
### Branch/PR Failing

https://github.com/apache/tvm/commit/1afd0593956066635ee49297b731726c9218c91c

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4158/pipeline/

### Flakiness

No

**Comment by driazati** [comment] 2022-08-25 15:46
actual failure is in the tests, duplicate of #12311

**Closed by driazati** 2022-08-25 15:46 UTC
Labels: needs-triage
