### ISSUE TITLE
[Bug] The source code installation of version 0.9.0 failed

### ISSUE THREAD

**Issue by Uhao-P** [apache/tvm#12065] opened 2022-07-12 12:07 UTC
### Expected behavior

Successful installation

### Actual behavior

Error following the documentation to get this far
`cd python; python setup.py install --user; cd ..`

Check setup.py and find that the following code causes an error
``` python
# Add tvmc configuration json files
for name in lib_path:
    candidate_path = os.path.abspath(os.path.join(os.path.dirname(name), "..", "configs"))
    if os.path.isdir(candidate_path):
        libs.append(candidate_path)
        break
```

### Environment

ubuntu18.04
tvm==0.9.0

**Comment by driazati** [comment] 2022-07-12 21:27
Closing this as a duplicate of #12065, but we definitely do want to get this fixed before the v0.9.0 release so thanks for flagging it

**Closed by driazati** 2022-07-12 21:27 UTC
Labels: type: bug
