### ISSUE TITLE
[Flaky Test] `tests/python/contrib/test_ethosu/test_replace_depthwise_conv2d.py::test_depthwise_conv2d_single[trial3]`

### ISSUE THREAD

**Issue by driazati** [apache/tvm#12841] opened 2022-09-19 19:42 UTC
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/contrib/test_ethosu/test_replace_depthwise_conv2d.py::test_depthwise_conv2d_single[trial3]`

<details>

```
[2022-09-19T18:44:28.351Z] tests/python/contrib/test_ethosu/test_replace_depthwise_conv2d.py::test_depthwise_conv2d_single[trial3] Fatal Python error: Segmentation fault
[2022-09-19T18:44:28.351Z] 
[2022-09-19T18:44:28.351Z] Thread 0x00007fc47f440700 (most recent call first):
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 400 in read
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 432 in from_io
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 967 in _thread_receiver
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 220 in run
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 285 in _perform_spawn
[2022-09-19T18:44:28.351Z] 
[2022-09-19T18:44:28.351Z] Current thread 0x00007fc48157a740 (most recent call first):
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/ethosu/vela/weight_compressor.py", line 174 in encode_weights
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/ethosu/vela/api.py", line 431 in npu_encode_weights
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/vela_api.py", line 232 in compress_weights
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/vela_api.py", line 168 in encode_weights
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/passes.py", line 353 in _encode_weights
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/passes.py", line 383 in _encode_weights_or_bias
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/passes.py", line 444 in _visit
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/_ffi/_ctypes/packed_func.py", line 81 in cfun
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/_ffi/_ctypes/packed_func.py", line 233 in __call__
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/tir/stmt_functor.py", line 59 in post_order_visit
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/passes.py", line 466 in collect_encoding_definitions
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/passes.py", line 567 in _ftransform
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/_ffi/_ctypes/packed_func.py", line 81 in cfun
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/_ffi/_ctypes/packed_func.py", line 233 in __call__
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/ir/transform.py", line 161 in __call__
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/passes.py", line 655 in _encode_constants
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/compiler.py", line 91 in lower_ethosu
[2022-09-19T18:44:28.351Z]   File "/workspace/python/tvm/relay/backend/contrib/ethosu/tir/compiler.py", line 251 in _lower_to_tir
[2022-09-19T18:44:28.351Z]   File "/workspace/tests/python/contrib/test_ethosu/test_replace_depthwise_conv2d.py", line 111 in test_depthwise_conv2d_single
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_callers.py", line 39 in _multicall
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_manager.py", line 80 in _hookexec
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_hooks.py", line 265 in __call__
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/python.py", line 1761 in runtest
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_callers.py", line 39 in _multicall
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_manager.py", line 80 in _hookexec
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_hooks.py", line 265 in __call__
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/runner.py", line 259 in <lambda>
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/runner.py", line 338 in from_call
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/runner.py", line 219 in call_and_report
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/runner.py", line 130 in runtestprotocol
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pytest_rerunfailures.py", line 497 in pytest_runtest_protocol
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_callers.py", line 39 in _multicall
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_manager.py", line 80 in _hookexec
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_hooks.py", line 265 in __call__
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/xdist/remote.py", line 110 in run_one_test
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/xdist/remote.py", line 91 in pytest_runtestloop
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_callers.py", line 39 in _multicall
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_manager.py", line 80 in _hookexec
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_hooks.py", line 265 in __call__
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/main.py", line 322 in _main
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/main.py", line 268 in wrap_session
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_callers.py", line 39 in _multicall
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_manager.py", line 80 in _hookexec
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/pluggy/_hooks.py", line 265 in __call__
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/xdist/remote.py", line 291 in <module>
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 1084 in executetask
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 220 in run
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 285 in _perform_spawn
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 267 in integrate_as_primary_thread
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 1060 in serve
[2022-09-19T18:44:28.351Z]   File "/opt/tvm-venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 1554 in serve
[2022-09-19T18:44:28.351Z]   File "<string>", line 8 in <module>
[2022-09-19T18:44:28.351Z]   File "<string>", line 1 in <module>
```

</details>

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4334/display/redirect

**Comment by ekalda** [comment] 2022-10-12 13:07
It looks like this is the caused by the same issue of segfaulting when calling Vela's weight encoder for which there are few issues raised and a fix in progress - https://github.com/apache/tvm/issues/12634#issuecomment-1276137695

**Comment by lhutton1** [comment] 2023-11-03 11:54
closing, same issue as #12634

**Closed by lhutton1** 2023-11-03 11:54 UTC
Labels: test: flaky, byoc:ethosu
