### ISSUE TITLE
[TEST][FLAKY] frontend/pytorch/test_forward.py::test_forward_nms 

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#6689] opened 2020-10-15 13:14 UTC
https://ci.tlcpack.ai/job/tvm/job/main/19/execution/node/380/log/

Could due to too close ties, perhaps we should construct nms test-cases differently that have no clear ties

**Comment by tqchen** [comment] 2020-10-15 13:14
cc @masahi @Laurawly

**Comment by masahi** [comment] 2020-10-15 15:11
cc @yongwww

**Comment by yongwww** [comment] 2020-10-26 15:34
@masahi @tqchen I failed to reproduce it on my environment. The flaky issue was introduced due to the accumulation of tiny difference of computations, especially for a large number of input boxes. I will send a pr to loosen the tolerance.

**Comment by masahi** [comment] 2020-10-27 05:12
@yongwww maybe setting rng manual seed via `torch.manual_seed(...)` help.

**Comment by masahi** [comment] 2021-04-12 05:27
Still has this problem 

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7824/1/pipeline

**Comment by denise-k** [comment] 2021-09-27 21:06
Hi folks, is this still active?

**Comment by masahi** [comment] 2021-09-28 05:07
I was able to reproduce the error after 30 runs, it is fixed in https://github.com/apache/tvm/pull/9140

**Closed** 2021-09-29 17:30 UTC
Labels: test: flaky
