### ISSUE TITLE
[Bug] [Relay] Error when compiling a simple ONNX model

### ISSUE THREAD

**Issue by luyaor** [apache/tvm#7202] opened 2021-01-04 12:13 UTC
## Description

When compiling following model with TVM, it will error.

The model(with ONNX as frontend) with error is as follows, check bug.onnx in bug2.zip.

![image](https://user-images.githubusercontent.com/7541296/103534130-40f31e80-4ec9-11eb-867e-76986a0e0693.png)

## Error Log

```
The Relay type checker is unable to show the following types match.
In particular dimension 0 conflicts: 3 does not match 1.
The Relay type checker is unable to show the following types match.
In particular `Tensor[(3), float32]` does not match `Tensor[(1), float32]`
note: run with `TVM_BACKTRACE=1` environment variable to display a backtrace.
```

### Environment

Python3, with tvm, onnx, you could also use Conda as `conda env create -f environment.yml`

tvm version: [`c31e338`](https://github.com/apache/tvm/commit/c31e338d5f98a8e8c97286c5b93b20caee8be602) Wed Dec 9 14:52:58 2020 +0900

1. Download [bug2.zip](https://github.com/apache/tvm/files/5764543/bug2.zip)

2. Run `python check.py`.

**Comment by jwfromm** [comment] 2021-01-05 03:45
Thanks for finding this bug, it's due to a bad assumption made in Prelu conversion about the input layout. The issue is fixed in https://github.com/apache/tvm/pull/7208 and I've confirmed the test script works with that change.

**Closed** 2021-01-05 08:26 UTC
