### ISSUE TITLE
[Bug] [TIR] T.if_then_else vanishes after blockize

### ISSUE THREAD

**Issue by MichaelJKlaiber** [apache/tvm#16224] opened 2023-12-11 20:13 UTC
T.if_then_else vanishes after blockize

```
from tvm.script import tir as T
from tvm import tir
from tvm.ir import IRModule   

@T.prim_func
def func(A: T.Buffer((128, 129), "float32"), B: T.Buffer((128, 129), "float32")):
    for i, j in T.grid(128, 129):
        with T.block("B"):
            vi, vj = T.axis.remap("SS", [i, j])
            B[vi, vj] = T.if_then_else(vj<129, A[vi, vj] * 2.0, 0, dtype="int32")
            
    
    
sch = tir.Schedule(func)
i, j = sch.get_loops(sch.get_block("B"))
print(sch.mod)
sch.blockize(j)
print(sch.mod)

```

### Expected behavior

```
# from tvm.script import ir as I
# from tvm.script import tir as T

@I.ir_module
class Module:
    @T.prim_func
    def main(A: T.Buffer((128, 129), "float32"), B: T.Buffer((128, 129), "float32")):
        T.func_attr({"global_symbol": "func"})
        # with T.block("root"):
        for i in range(128):
            with T.block("B_o"):
                vi_o = T.axis.spatial(128, i)
                vj_o = T.axis.spatial(1, 0)
                T.reads(A[vi_o, 0:129])
                T.writes(B[vi_o, 0:129])
                for j in range(129):
                    with T.block("B"):
                        vj_i = T.axis.spatial(129, j)
                        T.reads(A[vi_o, vj_i])
                        T.writes(B[vi_o, vj_i])
                        B[vi, vj] = T.if_then_else(vj < 129, A[vi, vj] * T.float32(2), T.float32(0))
```
### Actual behavior

```
@I.ir_module
class Module:
    @T.prim_func
    def main(A: T.Buffer((128, 129), "float32"), B: T.Buffer((128, 129), "float32")):
        T.func_attr({"global_symbol": "func"})
        # with T.block("root"):
        for i in range(128):
            with T.block("B_o"):
                vi_o = T.axis.spatial(128, i)
                vj_o = T.axis.spatial(1, 0)
                T.reads(A[vi_o, 0:129])
                T.writes(B[vi_o, 0:129])
                for j in range(129):
                    with T.block("B"):
                        vj_i = T.axis.spatial(129, j)
                        T.reads(A[vi_o, vj_i])
                        T.writes(B[vi_o, vj_i])
                        B[vi_o, vj_i] = A[vi_o, vj_i] * T.float32(2)
```

### Environment

main a9fcac1a47f4b57c1d9d828c7ed1d77452b02cc5
Dec10 23

### Steps to reproduce

```
from tvm.script import tir as T
from tvm import tir
from tvm.ir import IRModule   

@T.prim_func
def func(A: T.Buffer((128, 129), "float32"), B: T.Buffer((128, 129), "float32")):
    for i, j in T.grid(128, 129):
        with T.block("B"):
            vi, vj = T.axis.remap("SS", [i, j])
            B[vi, vj] = T.if_then_else(vj<129, A[vi, vj] * 2.0, 0, dtype="int32")
            
    
    
sch = tir.Schedule(func)
i, j = sch.get_loops(sch.get_block("B"))
print(sch.mod)
sch.blockize(j)
print(sch.mod)

```

Output:
```
# from tvm.script import ir as I
# from tvm.script import tir as T

@I.ir_module
class Module:
    @T.prim_func
    def main(A: T.Buffer((128, 129), "float32"), B: T.Buffer((128, 129), "float32")):
        T.func_attr({"global_symbol": "func"})
        # with T.block("root"):
        for i, j in T.grid(128, 129):
            with T.block("B"):
                vi, vj = T.axis.remap("SS", [i, j])
                T.reads(A[vi, vj])
                T.writes(B[vi, vj])
                B[vi, vj] = T.if_then_else(vj < 129, A[vi, vj] * T.float32(2), T.float32(0))
# from tvm.script import ir as I
# from tvm.script import tir as T

@I.ir_module
class Module:
    @T.prim_func
    def main(A: T.Buffer((128, 129), "float32"), B: T.Buffer((128, 129), "float32")):
        T.func_attr({"global_symbol": "func"})
        # with T.block("root"):
        for i in range(128):
            with T.block("B_o"):
                vi_o = T.axis.spatial(128, i)
                vj_o = T.axis.spatial(1, 0)
                T.reads(A[vi_o, 0:129])
                T.writes(B[vi_o, 0:129])
                for j in range(129):
                    with T.block("B"):
                        vj_i = T.axis.spatial(129, j)
                        T.reads(A[vi_o, vj_i])
                        T.writes(B[vi_o, vj_i])
                        B[vi_o, vj_i] = A[vi_o, vj_i] * T.float32(2)
```

### Triage

* tir
* tir:schedule
* tir: transform

cc @Hzfengsy @junrushao @quic-sanirudh @shingjan

**Comment by MichaelJKlaiber** [comment] 2023-12-11 20:14
@Hzfengsy

**Comment by Hzfengsy** [comment] 2023-12-12 04:26
Hi @MichaelJKlaiber. Thanks for the reporting. It's not a bug, as `vj` is bound to loop `j`, with range `[0, 129)`. So `vj < 129` is always true. The `blockize` step simplifies the expr and removes the `T.if_then_else`. Once you change the predicate from `vj < 129` to `vj < 128`, everything looks good.

Please let me know if it makes sense. If so, feel free to close the issue.

**Closed** 2023-12-19 17:06 UTC
Labels: type: bug, needs-triage
