### ISSUE TITLE
[TEST][FLAKY] tests/python/frontend/tensorflow/test_forward.py::test_forward_combined_nms

### ISSUE THREAD

**Issue by ekalda** [apache/tvm#8140] opened 2021-05-26 10:43 UTC
That test failed on a whitespace change, which looks suspicious... https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8124/1/pipeline/

**Comment by masahi** [comment] 2021-06-08 08:20
The same error happened at https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8126/8/pipeline

@trevor-m This is `q != 1` case (each class has its own box), the new code path from https://github.com/apache/tvm/commits/main is not used.

**Comment by masahi** [comment] 2021-06-08 19:38
I was informed that there was another failure at https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8179/6/pipeline/ which does use the new code path. I was able to get it fail after 970 trials.

**Comment by masahi** [comment] 2021-06-08 19:45
I'm not sure if the two flaky ness are due to the same reason, in which case yes, we need to look at the core NMS loop. Are you sure the conversion logic in TF frontend for `q != 1` case is correct?

**Comment by masahi** [comment] 2021-06-08 21:34
The reproduction I got locally was due to a tie in scores. The top 2 scores have identical scores but the order is swapped between TF / TVM:

```
Mismatched elements: 8 / 256 (3.12%)
Max absolute difference: 1.8291236
Max relative difference: 21.120028
 x: array([[[ 0.613913, -0.086606,  0.650708,  0.433798],
        [ 0.398791,  1.742517,  1.710477,  0.569614],
        [ 0.736459,  0.409182,  0.026915, -0.968162],...
 y: array([[[ 0.398791,  1.742517,  1.710477,  0.569614],
        [ 0.613913, -0.086606,  0.650708,  0.433798],
        [ 0.736459,  0.409182,  0.026915, -0.968162],...
```

**Comment by tqchen** [comment] 2021-06-23 16:57
normally we should construct test cases to ensure there are no ties

**Comment by mbrookhart** [comment] 2021-06-24 15:42
I'm seeing flakiness in this test in about 1/3 of CI jobs, it's becoming a real problem to getting other PRs merged. Should we think about disabling this test until we can resolve the flakiness?

**Comment by trevor-m** [comment] 2021-06-24 16:32
I'm fine with disabling the test for now, sorry I haven't had a chance to look into the flakiness yet.

**Comment by masahi** [comment] 2021-06-29 07:30
Another failure from the `(1, 64, 20, 4)` workload despite the fix in https://github.com/apache/tvm/pull/8335. `Mismatched elements: 65 / 256 (25.4%)` suggests that something is off @trevor-m 
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8358/2/pipeline

**Comment by tqchen** [comment] 2021-07-20 20:13
@masahi please followup to see if we can close this issue

**Closed** 2021-07-20 21:03 UTC
